name: CI Pipeline # 工作流名称

on: # 触发条件
  push: # 代码推送时触发
    branches: ['main'] # 仅 main 分支
  pull_request: # PR 时触发
    branches: ['main']

jobs: # 定义任务
  test: # 任务名称
    runs-on: ubuntu-latest # 运行环境（GitHub 托管的 Runner）

    steps: # 任务步骤
      - name: Checkout code # 检出代码
        uses: actions/checkout@v4

      - name: Setup Node.js # 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 指定版本

      - name: Install and Build
        run: |
          npm install
          npm run build  # 生成 dist 文件夹

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动生成的 Token
          publish_dir: ./dist # 要部署的目录
