name: CI Pipeline

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: npm run build

  deploy:
    needs: [install, lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
