name: CI Pipeline # 工作流名称

on: # 触发条件
  push: # 代码推送时触发
    branches: ['main'] # 仅 main 分支
  pull_request: # PR 时触发
    branches: ['main']

jobs: # 定义任务
  test: # 任务名称
    runs-on: ubuntu-latest # 运行环境（GitHub 托管的 Runner）

    steps: # 任务步骤
      - name: Checkout code # 检出代码
        uses: actions/checkout@v4

      - name: Setup Node.js # 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 指定版本

      - name: Install dependencies # 安装依赖
        run: npm install

      - name: Run build # 运行测试
        run: npm run build
